import React from 'react'

function EducationData() {
    return (
        <div>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequuntur dolore, at enim maxime unde, est placeat omnis possimus sequi harum sunt ex deleniti! Porro, autem dignissimos ea explicabo magni laboriosam facere eveniet alias maiores, nobis ipsa. Reprehenderit atque possimus at pariatur molestiae voluptates assumenda neque fuga corporis ipsam consequuntur dolorum autem labore voluptas commodi dolore molestias, fugit nostrum sint doloribus, nihil cupiditate suscipit ullam. A minima error quia sed, corporis, eveniet quidem suscipit minus natus aliquid necessitatibus quis saepe accusantium aliquam similique, corrupti id quod inventore at? Molestias quae, maiores explicabo voluptatem esse architecto numquam nulla quibusdam assumenda accusamus ratione id doloribus. Sequi omnis sit iusto inventore, corrupti non atque officia. Ea, omnis laudantium fuga totam nihil quo quam consequuntur sunt aliquam laborum sequi. Minima iure, maiores rerum sit sed vero omnis totam nihil autem, hic eum veritatis dolorum ut ea fugiat cupiditate incidunt perspiciatis reiciendis, dignissimos excepturi doloribus repudiandae cumque! Fuga sapiente at illo, quibusdam suscipit quos aut autem error eaque voluptate non doloribus quaerat. Atque eos consequatur quae nisi velit tenetur obcaecati maiores laborum aperiam fuga neque nulla dolores quos doloribus quam veritatis error at quisquam id cum, libero sint recusandae distinctio! Temporibus itaque, aliquam ea dolores consectetur adipisci velit necessitatibus, nemo repellat earum illo sequi, consequatur doloribus tempora molestiae! Quae dignissimos aut maxime in obcaecati aspernatur quam ullam impedit sequi vitae, minima fugit molestiae incidunt similique, animi numquam placeat cumque eligendi voluptate sapiente repellat ipsum iure nostrum? Ipsa, doloribus! Quos saepe voluptate eligendi, enim ut eaque, quo asperiores laudantium consectetur fugiat necessitatibus eius, quisquam est corrupti ratione commodi! Mollitia aspernatur, blanditiis dignissimos alias obcaecati numquam quibusdam, sequi exercitationem amet sed illum ducimus distinctio consectetur nemo quo quae harum pariatur voluptatibus voluptatem, veritatis repudiandae deleniti at nostrum. Fuga quis ex tempora? Eveniet, reprehenderit autem? Obcaecati iste quam explicabo!</p>
        </div>
    )
}

export default EducationData
